# Env definition file for creating environment via conda

name: cmatools-docs-env
channels:
 - conda-forge
dependencies:
 - python=3.9
 - black
 - sphinx
 - sphinx_rtd_theme
 - sphinx-argparse
 - sphinx-gallery
 - pip

 - pip:
   - sphinxcontrib-mermaid
