# Env definition file for creating environment via conda

name: cmatools-dev-env
channels:
 - conda-forge
dependencies:
 - python=3.9
 - iris>=3.0
 - black
 - pre-commit
 - pydap
 - isort
 - flake8
 - nccmp
 - libnetcdf
 - humanize
 - coverage
 - pytest
 - pytest-cov
 - myst-parser
 - sphinx
 - sphinx_rtd_theme
 - sphinx-argparse
 - sphinx-gallery
 - sphinxcontrib-mermaid
 - numpydoc
 - pipreqs
 - cdsapi
 - numpy>=1.19
 - pandas
 - pip

# Removed from dev environment to speed up builds, installs, uninstalls
# - xarray
# - jupyter
# - holoviews
# - geoviews
