# Env definition file for creating environment via conda

name: cmatools-env
channels:
 - conda-forge
dependencies:
 - python=3.7
 - iris=2.4
 - black
 - nccmp
 - coverage
 - pytest
 - sphinx
 - sphinx_rtd_theme
 - sphinx-argparse
 - sphinx-gallery
 - pip

 - pip:
   - sphinxcontrib-mermaid