# Env definition file for creating environment via conda

name: cmadocs-env
channels:
 - conda-forge
dependencies:
 - python=3.7
 - black
 - sphinx
 - sphinx_rtd_theme
 - sphinx-argparse
 - sphinx-gallery
 - pip

 - pip:
   - sphinxcontrib-mermaid
