# ####################################################################
# GitHub workflow action file
# Tests that the Sphinx documentation builds successfully
# ####################################################################

# Name for workflow (also displayed on the associated badges)
name: docs

# Runs on all pushes to the repo
on: [push]

# Set environment variables so this workflow action is easy to re-use in other repos
env:
  REPO_NAME: cmatools
  CONDA_ENV: cmadocs-env

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        conda update conda
        conda env create -f environment_docs.yml
    - name: conda check
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        which python
        python --version
        conda info --envs
        conda info
    - name: Install package
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        pip  install .
    - name: Test Sphinx docs build
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        cd scripts/docs
        chmod +x build-sphinx-docs.sh
        ./build-sphinx-docs.sh