name: docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        conda update conda
        conda env create -f environment_docs.yml
    - name: conda check
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmadocs-env
        which python
        python --version
        conda info --envs
        conda info
    - name: Install package
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmadocs-env
        python setup.py install
    - name: Test Sphinx docs build
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmadocs-env
        cd scripts/docs
        chmod +x build-sphinx-docs.sh
        ./build-sphinx-docs.sh
