# Name for workflow (also displayed on the associated badges)
name: lint

on: [push]

# Set environment variables so this workflow action is easy tore-use in other repos
env:
  REPO_NAME: cmatools
  CONDA_ENV: cmatools-env

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        conda update conda
        conda env create -f environment.yml
    - name: conda check
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        which python
        python --version
        conda info --envs
        conda info
    - name: Install cmatools
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        python setup.py install
    - name: Lint with flake8
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with coverage
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        cd bin
        chmod +x test-coverage-remote.sh
        ./test-coverage-remote.sh
      env:
        REMOTE_TESTS: True