# ####################################################################
# GitHub workflow action file
# Checks recent gh-pages website builds
# ####################################################################

# Name for workflow (also displayed on the associated badges)
name: site

# Controls when the action will run. Triggers the workflow only if docs workflow succeeds
on: [push]

env:
  SITE: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Confirm pages
      run: |
        curl \
          -H "Accept: application/vnd.github.v3+json" \
          -u ${{ secrets.ACCESS_TOKEN }} \
          https://api.github.com/repos/cma-open/cmatools/pages

    - name: Confirm current page build status
      id: check
      run: |
        curl \
          -H "Accept: application/vnd.github.v3+json" \
          -u ${{ secrets.ACCESS_TOKEN }} \
          https://api.github.com/repos/cma-open/cmatools/pages/builds/latest
        echo "::set-output name=date::$(date +'%Y.%m.%d.%Hh%Mm')"

    - name: Confirm current page build status
      id: alt
      run: |
        ath="Accept: application/vnd.github.v3+json"
        url="https://api.github.com/repos/cma-open/cmatools/pages/builds/latest"
        response=$(curl -H "$ath" -u ${{ secrets.ACCESS_TOKEN }} "$url")
#        response2=${{fromJson($response)}}
        echo " ---- "
        echo "$response"
        echo " ---- "
#        echo "$response2"
        echo " --- "
        echo "::set-output name=body::${{ toJson("$response") }}"

    - name: Test the job steps outputs
      run: |
        echo ${{ steps.check.outputs.date }}
        echo ${{ steps.check.outcome }}
        echo ${{ steps.alt.outputs.body }}
        echo ${{fromJson(steps.alt.outputs.body).status}}